platform :ios, '9.0'
use_frameworks!
target 'MachineLogin' do
pod 'Alamofire', '~> 4.5' 
pod 'Kingfisher', '~> 4.1' 
pod 'IQKeyboardManagerSwift', '~> 5.0' 
pod 'FAPanels', '~> 0.3' 
pod 'SwifterSwift', '~> 4.0' 
pod 'SwiftyJSON', '4.0.0-alpha.1' 
pod 'PKHUD', '~> 5.0'
end